// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzrJEVATh5ox4oHPeu_sMSb7Q0T-uvEc',
    appId: '1:542588670255:web:e6fba0e5cd98835af8d1da',
    messagingSenderId: '542588670255',
    projectId: 'rbabusattendance',
    authDomain: 'rbabusattendance.firebaseapp.com',
    storageBucket: 'rbabusattendance.firebasestorage.app',
    measurementId: 'G-3P7D9RDWWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoD9BYMnaWYsF6evuYR-rQhQHXxYBbzok',
    appId: '1:542588670255:android:2d5bbe753a4512dff8d1da',
    messagingSenderId: '542588670255',
    projectId: 'rbabusattendance',
    storageBucket: 'rbabusattendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnM0L1_fZmPLsCLJpQnoyAu2YmlGL1nck',
    appId: '1:542588670255:ios:3c83eecda103bd80f8d1da',
    messagingSenderId: '542588670255',
    projectId: 'rbabusattendance',
    storageBucket: 'rbabusattendance.firebasestorage.app',
    iosBundleId: 'com.example.rbaBusAttendance',
  );
}
